
# nav
nav:
- HOME: /
- ABOUT: /about
- ARCHIVE: /archives
- GITHUB: https://github.com/QZEming
- CSDN: https://blog.csdn.net/zemprogram/

# info
title: 前端小黑
avatar: /img/assets/logo.png
favicon: /img/assets/favicon.ico

# animation
topCanvas: true
bgCanvas: true
# aside
tagsLen: 7
categoriesLen: 5
newpostsLen: 5

# 404img
errorImg: /img/assets/404error.gif